# Generated by Django 2.0.9 on 2026-08-21 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=255)),
                ('attribute_value', models.CharField(max_length=500)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(max_length=100, unique=True)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('product_category', models.CharField(blank=True, max_length=255, null=True)),
                ('product_sub_category', models.CharField(blank=True, max_length=255, null=True)),
                ('collection_name', models.CharField(blank=True, max_length=255, null=True)),
                ('color_collection', models.CharField(blank=True, max_length=255, null=True)),
                ('product_color', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.CharField(max_length=500)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('bullets', models.TextField(blank=True, null=True)),
                ('set_includes', models.TextField(blank=True, null=True)),
                ('product_weight', models.CharField(blank=True, max_length=100, null=True)),
                ('materials', models.CharField(blank=True, max_length=500, null=True)),
                ('product_dimensions', models.CharField(blank=True, max_length=500, null=True)),
                ('assembly_required', models.CharField(blank=True, max_length=100, null=True)),
                ('is_set', models.CharField(blank=True, max_length=100, null=True)),
                ('stackable', models.CharField(blank=True, max_length=100, null=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=255, null=True)),
                ('item_cost', models.CharField(blank=True, max_length=100, null=True)),
                ('map_price', models.CharField(blank=True, max_length=100, null=True)),
                ('msrp', models.CharField(blank=True, max_length=100, null=True)),
                ('image_1', models.TextField(blank=True, null=True)),
                ('image_2', models.TextField(blank=True, null=True)),
                ('image_3', models.TextField(blank=True, null=True)),
                ('image_4', models.TextField(blank=True, null=True)),
                ('image_5', models.TextField(blank=True, null=True)),
                ('shopify_category', models.CharField(blank=True, max_length=500, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('alternative_categories', models.TextField(blank=True, null=True)),
                ('requires_manual_review', models.BooleanField(default=False)),
                ('classification_status', models.CharField(default='Pending', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='categoryattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='shopifyapp.Product'),
        ),
    ]
