# Generated by Django 2.0.9 on 2026-08-22 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('full_path', models.TextField()),
                ('is_leaf', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='shopifyapp.TaxonomyCategory')),
            ],
        ),
    ]
