# Generated by Django 2.0.9 on 2026-08-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyapp', '0003_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detected_attributes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
