# Generated by Django 2.0.9 on 2026-08-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyapp', '0004_product_detected_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomycategory',
            name='taxonomy_attributes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
