# Generated by Django 2.0.9 on 2026-08-23 05:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyapp', '0005_taxonomycategory_taxonomy_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], db_index=True, default='Pending', max_length=30)),
                ('batch_size', models.PositiveIntegerField(default=500)),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('processed_products', models.PositiveIntegerField(default=0)),
                ('successful_products', models.PositiveIntegerField(default=0)),
                ('manual_review_products', models.PositiveIntegerField(default=0)),
                ('failed_products', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='categoryattribute',
            options={'ordering': ['attribute_name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='categoryattribute',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoryattribute',
            name='attribute_handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='categoryattribute',
            name='attribute_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='categoryattribute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoryattribute',
            name='source',
            field=models.CharField(default='taxonomy', max_length=50),
        ),
        migrations.AddField(
            model_name='categoryattribute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='categoryattribute',
            name='value_handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='categoryattribute',
            name='value_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='classification_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='classification_evidence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='classified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='image_error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_processing_status',
            field=models.CharField(default='Not Processed', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='manual_review_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shopify_category_id',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='categoryattribute',
            name='approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='classification_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Classified', 'Classified'), ('Manual Review', 'Manual Review'), ('Approved', 'Approved'), ('Error', 'Error')], db_index=True, default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_number',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='requires_manual_review',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='shopify_category',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomycategory',
            name='is_leaf',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='taxonomycategory',
            name='shopify_id',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AddIndex(
            model_name='categoryattribute',
            index=models.Index(fields=['product', 'approved'], name='shopifyapp__product_3a4eb3_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryattribute',
            index=models.Index(fields=['attribute_id'], name='shopifyapp__attribu_d1beb8_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryattribute',
            index=models.Index(fields=['value_id'], name='shopifyapp__value_i_47ad66_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['classification_status'], name='shopifyapp__classif_466ba3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['requires_manual_review'], name='shopifyapp__require_dba997_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['confidence_score'], name='shopifyapp__confide_bfc2b3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shopify_category_id'], name='shopifyapp__shopify_86a8b7_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonomycategory',
            index=models.Index(fields=['is_leaf'], name='shopifyapp__is_leaf_baca3c_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonomycategory',
            index=models.Index(fields=['name'], name='shopifyapp__name_438b26_idx'),
        ),
    ]
